# This is a basic workflow to help you get started with Actions

name: CI

# Controls when the workflow will run
on:
  # Triggers the workflow on push or pull request events but only for the "main" branch
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  build:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - uses: actions/checkout@v3

      # Runs a single command using the runners shell
      - name: Run a one-line script
        run: echo Hello, world!

      # Runs a set of commands using the runners shell
      - name: Run a multi-line script
        run: |
           curl -o- "https://dl-cli.pstmn.io/install/linux64.sh" | sh
           postman login --with-api-key ${{secrets.API_KEY}}
           postman collection run "20898840-48c3bd97-31ea-4c44-b838-c1cc50ac75e7" -e "20898840-82eb4199-9056-4b9b-8e5e-c580ec0cdc79"
           - name: Create Awesome Badge
             uses: 
              schneegans/dynamic-badges-action@v1.6.0
              with:
              auth: ${{ secrets.GIST_SECRET }}
             gistID: <gist-ID>
            filename: test.json
            label: Hello
            message: World
            color: orange
